<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\ProjectBuildProperties.targets" />

	<ItemGroup>
	  <PackageReference Include="Microsoft.Graph" />
	  <PackageReference Include="Microsoft.Identity.Client" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TqkLibrary.Http\TqkLibrary.Http.csproj" />
	</ItemGroup>

</Project>
