<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\ProjectBuildProperties.targets" />

	<ItemGroup>
		<PackageReference Include="MailKit" />
		<PackageReference Include="Nito.AsyncEx" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\TqkLibrary.Http\TqkLibrary.Http.csproj" />
	  <ProjectReference Include="..\TqkLibrary.Http.Api.Proxy\TqkLibrary.Http.Api.Proxy.csproj" />
	</ItemGroup>
	
</Project>
