<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\ProjectBuildProperties.targets" />
	
	<ItemGroup>
		<PackageReference Include="Nito.AsyncEx" />
		<PackageReference Include="Microsoft.CSharp" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TqkLibrary.Http\TqkLibrary.Http.csproj" />
	</ItemGroup>

</Project>
